name: Build Transform Images

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
    pull_request:
        branches:
            - "dev"
jobs:
    build-code:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and Test Code Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/code DOCKER=docker test-image
            - name: Save images
              # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/code docker-save-image
            - name: Upload images
              # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                name: images
                path: artifacts/*
                retention-days: 1
    build-language:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and Test Language Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image
                  make -C transforms/language DOCKER=docker test-image
            - name: Save images
              # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/language docker-save-image
            - name: Upload images
              # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                  name: images
                  path: artifacts/*
    build-universal:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and Test Universal Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/universal DOCKER=docker test-image
            - name: Save images
                  # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/universal docker-save-image
            - name: Upload images
            # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                  name: images
                  path: artifacts/*
    build-kfp-components:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Build 
            run: |
               make -C kfp/kfp_ray_components DOCKER=docker image
          - name: Save images
          # if: ${{ github.event_name != 'pull_request' }}
            run: make -C kfp/kfp_ray_components docker-save-image
    build-tools:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and Test Tool images
              run: |
                  make -C tools/ingest2parquet DOCKER=docker test-image
    push-images:
        name: Push images with latest tag
        runs-on: ubuntu-latest
        env:
           DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
           DOCKER_REGISTRY_KEY: ${{ secrets.DOCKER_REGISTRY_KEY }}
        needs: [test-make, test-python-lib, test-ray-lib, test-kfp-v1]
        # if: ${{ github.event_name != 'pull_request' && github.repository == 'IBM/data-prep-kit' }}
        steps:
        - uses: actions/checkout@v3
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            path: artifacts/*
            name: images
        - name: Load images
          run: |
               make -C transforms docker-load-image
               make -C kfp-kfp_ray_componenets docker-load-image
        - id: version
          name: Infer version
          run: |
            publish_images='false'
            if  [[ ${GITHUB_REF} == refs/heads/dev ]] ;
            then
              publish_images='true'
            fi
            echo ::set-output name=publish_images::$publish_images
        - name: Publish images
          if: ${{ steps.version.outputs.publish_images == 'true' }}
#           run: make -C transforms -C kfp-kfp_ray_componenets publish
          run: echo "make -C transforms -C kfp-kfp_ray_componenets publish"


