name: Build Transform Images

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
    pull_request:
        branches:
            - "dev"
jobs:
    build-code:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Free up space in github runner
              # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: |
                  df -h
                  sudo rm -rf "/usr/local/share/boost"
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/share/swift /usr/lib/jvm /usr/local/.ghcup
                  sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
                  df -h
            - name: Build and Test Code Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/code DOCKER=docker test-image
            - name: Print space
               # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: df -h
            - name: Save images
              # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/code docker-save-image
            - name: Upload images
              # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                name: images-code
                path: artifacts/*
                retention-days: 1
    build-language:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Free up space in github runner
              # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: |
                  df -h
                  sudo rm -rf "/usr/local/share/boost"
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/share/swift /usr/lib/jvm /usr/local/.ghcup
                  sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
                  df -h
            - name: Build and Test Language Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image
                  make -C transforms/language DOCKER=docker test-image
            - name: Print space
              # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: df -h
            - name: Save images
              # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/language docker-save-image
            - name: Upload images
              # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                  name: images-language
                  path: artifacts/*
    build-universal:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Free up space in github runner
              # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: |
                  df -h
                  sudo rm -rf "/usr/local/share/boost"
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/share/swift /usr/lib/jvm /usr/local/.ghcup
                  sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
                  df -h
            - name: Build and Test Universal Transforms
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/universal DOCKER=docker test-image
            - name: Print space
               # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
              run: df -h
            - name: Save images
                  # if: ${{ github.event_name != 'pull_request' }}
              run: make -C transforms/universal docker-save-image
            - name: Upload images
            # if: ${{ github.event_name != 'pull_request' }}
              uses: actions/upload-artifact@v3
              with:
                  name: images-universal
                  path: artifacts/*
    build-kfp-components:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Free up space in github runner
            # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
            run: |
                df -h
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/share/swift /usr/lib/jvm /usr/local/.ghcup
                sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
                df -h
          - name: Build 
            run: |
               make -C kfp/kfp_ray_components DOCKER=docker image
          - name: Print space
               # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
            run: df -h
          - name: Save images
          # if: ${{ github.event_name != 'pull_request' }}
            run: make -C kfp/kfp_ray_components docker-save-image
          - name: Upload images
            # if: ${{ github.event_name != 'pull_request' }}
            uses: actions/upload-artifact@v3
            with:
                name: images-kfp
                path: artifacts/*
    build-tools:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and Test Tool images
              run: |
                  make -C tools/ingest2parquet DOCKER=docker test-image
    push-images:
        name: Push images with latest tag
        runs-on: ubuntu-latest
        env:
           DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
           DOCKER_REGISTRY_KEY: ${{ secrets.DOCKER_REGISTRY_KEY }}
        needs: [build-code, build-language, build-universal, build-kfp-components]
        # if: ${{ github.event_name != 'pull_request' && github.repository == 'IBM/data-prep-kit' }}
        steps:
        - uses: actions/checkout@v3
        - name: Free up space in github runner
            # Free space as indicated here : https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          run: |
                df -h
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/share/powershell /usr/share/swift /usr/lib/jvm /usr/local/.ghcup
                sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
                df -h
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            path: artifacts/*
            pattern: images-*
        - name: Load code images
          run: |
               make -C transforms docker-load-image
               make -C kfp-kfp_ray_componenets docker-load-image
        - id: version
          name: Infer version
          run: |
            publish_images='false'
            if  [[ ${GITHUB_REF} == refs/heads/dev ]] ;
            then
              publish_images='true'
            fi
            echo ::set-output name=publish_images::$publish_images
        - name: Publish images
          if: ${{ steps.version.outputs.publish_images == 'true' }}
#           run: make -C transforms -C kfp-kfp_ray_componenets publish
          run: echo "make -C transforms -C kfp-kfp_ray_componenets publish"


