name: Build, Test, and upload Transform images to quay.io

on:
    release:
        types:
            - published
    workflow_dispatch:

jobs:
    build-images:
        name: Build and check images
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # for setuptools-scm
                  fetch-depth: 0
            - name: Build Package for pypi
              run: |
                  make -C transforms image test-image
    publish-images:
        name: Publish packages to quay.io
        # disabled
        if: false
        runs-on: ubuntu-22.04
        needs: build-images

        steps:
            - name: Push images to quay.io registry
              run: |
                  make -C transforms publish
