name: Test CI

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
    pull_request:
        branches:
            - "dev"
jobs:
    test-lib:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test data-processing-lib/ray
              run: |
                  make -C data-processing-lib/ray DOCKER=docker venv test
    test-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Code Transforms
              run: |
                  make -C transforms/code DOCKER=docker venv test-src
    test-universal:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Universal Transforms
              run: |
                  make -C transforms/universal DOCKER=docker venv test-src
    test-tools:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test tools
              run: |
                  make -C tools DOCKER=docker venv test
    test-kfp-lib:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test KFP lib
              run: |
                  source kind/requirements.env
                  export PATH=$PATH:/tmp/
                  curl -Lo /tmp/kind https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64
                  curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
                  chmod 700 /tmp/get_helm.sh
                  HELM_INSTALL_DIR=/tmp/ /tmp/get_helm.sh -v v${HELM_VERSION} --no-sudo
                  chmod 777 /tmp/helm
                  chmod 777 /tmp/kind
                  curl -L https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /tmp/kubectl
                  chmod 777 /tmp/kubectl
                  curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /tmp/mc
                  chmod +x /tmp/mc
                  export DEPLOY_KUBEFLOW=0
                  make -C kind setup 
                  make -C kfp/kfp_support_lib build test
    test-kfp-workflow-run:
        runs-on: ubuntu-latest
        steps:
            - name: Check space
              run:  df -h
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
              # this might remove tools that are actually needed,
              # if set to "true" but frees about 6 GB
                tool-cache: true

                # all of these default to true, but feel free to set to
                # "false" if necessary for your workflow
                android: true
                dotnet: true
                haskell: true
                large-packages: true
                swap-storage: true
            - name: Check space
              run:  df -h
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test KFP worflow run
              run: |
                  source kind/requirements.env
                  export PATH=$PATH:/tmp/
                  curl -Lo /tmp/kind https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64
                  curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
                  chmod 700 /tmp/get_helm.sh
                  HELM_INSTALL_DIR=/tmp/ /tmp/get_helm.sh -v v${HELM_VERSION} --no-sudo
                  chmod 777 /tmp/helm
                  chmod 777 /tmp/kind
                  curl -L https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /tmp/kubectl
                  chmod 777 /tmp/kubectl
                  curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /tmp/mc
                  chmod +x /tmp/mc
                  make -C kind setup
                  make -C kfp/transform_workflows venv build
                  make -C kfp/transform_workflows/universal/noop upload
                  make -C kfp/transform_workflows/universal/noop test

