name: Test Transform Images

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
            - "releases/**"
    pull_request:
        branches:
            - "dev"
            - "releases/**"
jobs:
    test-code-images:
        runs-on: ubuntu-22.04
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Code Transform Images
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/code DOCKER=docker test-image
    test-language-images:
        runs-on: ubuntu-22.04
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Language Transform Images
              run: |
                  make -C data-processing-lib DOCKER=docker image
                  make -C transforms/language DOCKER=docker test-image
    test-universal-images:
        runs-on: ubuntu-22.04
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Universal Transform Images
              run: |
                  make -C data-processing-lib DOCKER=docker image 
                  make -C transforms/universal DOCKER=docker test-image
    test-tool-images:
        runs-on: ubuntu-22.04
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test Tool images
              run: |
                  make -C tools/ingest2parquet DOCKER=docker test-image
